name: build

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: vscode-linux-x64
          - os: windows-latest
            target: vscode-win32-x64
          - os: macos-13
            target: vscode-darwin-x64
          - os: macos-14
            target: vscode-darwin-arm64

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run gulp ${{ matrix.target }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}
          path: ../VSCode-*
